# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b6a9eba133b045986dbf8515b649598722cb37e14a1208a0e29b6d0c8f8f8f7cc9e5c003559122f60ff27fcd9ce9d9fcc95787a2340704ce6e82a3f34eac317

test:
  secret_key_base: 724fccfeb10afd2285cbf72ea620c7b3ecb46e5cce4da5d3abaad98e0a2b13feef2fad994374350f85a1473a6c634fd3229a985191850f9bbc5f6ae940469ee6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
